### ISSUE TITLE
Material Presets and Style Presets menu unable to load - No access to Proxy

### ISSUE THREAD

**Issue by MaheshinderSingh** [semontesdeoca/MNPR#25]
Hi, I've been having an issue where when I click on the Style presets I'm prompted with this message:

import mnpr_runner
mnpr_runner.openPresets()
SYSTEM CHECK FOR MNPR
-> SYSTEM CHECK SUCCESSFUL
# Error: WindowsError: file C:/Users/3d136maheshi/Documents/maya/2018/scripts\mnpr_presets.py line 113: 3 # 

And when I click on the material presets I'm prompted with a similar message:

import mnpr_runner
mnpr_runner.openMaterialPresets()
SYSTEM CHECK FOR MNPR
-> SYSTEM CHECK SUCCESSFUL
# Error: WindowsError: file C:/Users/3d136maheshi/Documents/maya/2018/scripts\mnpr_matPresets.py line 374: 3 # 

I've had no trouble with the other important buttons thus far so I was wondering how I could fix this. My only real concern is being able to use the proxy feature, as I can save out styles seperately using the preset section in the attributes page.

If you could help me solve these issues or give me a preset file for the proxy so I could turn objects into them I'd be really grateful.

Thank you.

**Comment by semontesdeoca** [comment]
This happens because you put the files in the scripts folder within Maya and now it can't find the presets. Please delete the files you put in your scripts folder and re-install MNPR in the correct way. Let's continue troubleshooting this issue in [this thread](https://github.com/semontesdeoca/MNPR/issues/24)
